import spacy
nlp = spacy.load('en_core_web_sm')

text = """Contractor Contractor Contractor FUJIFILM Holdings America Corporation Brooklyn NY I would like a position where I can use my technical experience to execute new ventures in a group environment and further develop my technical skills to compliment my current experience Work Experience Contractor FUJIFILM Holdings America Corporation Valhalla NY October 2018 to Present Maintain Fujifilm America s web content on a proprietary CMS Build plugins and page templates for WordPress sites Build new websites on Google Sites and WordPress Develop Google Apps Scripts Web Developer BrandStar BMGcreative Fort Lauderdale FL April 2016 to April 2018 Build and maintain WordPress WooCommerce and Magento websites Allocate and manage web servers for company assets Improve page load speed and fix SEO content issues Implement Google Analytics lead tracking Contractor Nova Southeastern University Davie FL April 2015 to September 2015 Migrate content to Hannon Hill s Cascade Server Front end Developer Morris4x4Center Fort Lauderdale FL November 2013 to November 2014 Develop and maintain Magento website Front end Developer plantANT Davie FL November 2011 to November 2013 Develop and maintain php websites with MySQL Education Computer Science University of Central Florida Orlando FL August 2007 to August 2010 AA College Academy Broward College Davie FL August 2005 to August 2007 Skills HTML 5 6 years CSS3 6 years Javascript 6 years PHP 6 years MySQL 6 years Ajax 6 years JQuery 6 years JSON 6 years Wordpress 3 years Ecommerce 2 years Photoshop 6 years Linux 6 years Windows 6 years Content Management 6 years Data Entry 6 years DNS 2 years Email Marketing 2 years Quality Assurance 6 years SEO 6 years User Experience Design 6 years User Interface Design 6 years Front End 6 years UI 6 years Front End 6 years Links http marcelm org Assessments Critical Thinking Expert July 2019 Using logic to solve problems Full results https share indeedassessments com share assignment rmzl2fwen1fwx9g3 Indeed Assessments provides skills tests that are not indicative of a license or certification or continued development in any professional field """

def summarize(sentence):
    doc = nlp(sentence)
    for ent in doc.ents:
        print(f"Text: {ent.text[0:30] :{35}}", f"range: {ent.start_char} to {ent.end_char}{'':{35}}" , f"Label: {ent.label_}")

def NerText(sentence):
    doc = nlp(sentence)
    return " ".join([ent.text for ent in doc.ents])


if __name__ == '__main__':
    text = """Contractor Contractor Contractor FUJIFILM Holdings America Corporation Brooklyn NY I would like a position where I can use my technical experience to execute new ventures in a group environment and further develop my technical skills to compliment my current experience Work Experience Contractor FUJIFILM Holdings America Corporation Valhalla NY October 2018 to Present Maintain Fujifilm America s web content on a proprietary CMS Build plugins and page templates for WordPress sites Build new websites on Google Sites and WordPress Develop Google Apps Scripts Web Developer BrandStar BMGcreative Fort Lauderdale FL April 2016 to April 2018 Build and maintain WordPress WooCommerce and Magento websites Allocate and manage web servers for company assets Improve page load speed and fix SEO content issues Implement Google Analytics lead tracking Contractor Nova Southeastern University Davie FL April 2015 to September 2015 Migrate content to Hannon Hill s Cascade Server Front end Developer Morris4x4Center Fort Lauderdale FL November 2013 to November 2014 Develop and maintain Magento website Front end Developer plantANT Davie FL November 2011 to November 2013 Develop and maintain php websites with MySQL Education Computer Science University of Central Florida Orlando FL August 2007 to August 2010 AA College Academy Broward College Davie FL August 2005 to August 2007 Skills HTML 5 6 years CSS3 6 years Javascript 6 years PHP 6 years MySQL 6 years Ajax 6 years JQuery 6 years JSON 6 years Wordpress 3 years Ecommerce 2 years Photoshop 6 years Linux 6 years Windows 6 years Content Management 6 years Data Entry 6 years DNS 2 years Email Marketing 2 years Quality Assurance 6 years SEO 6 years User Experience Design 6 years User Interface Design 6 years Front End 6 years UI 6 years Front End 6 years Links http marcelm org Assessments Critical Thinking Expert July 2019 Using logic to solve problems Full results https share indeedassessments com share assignment rmzl2fwen1fwx9g3 Indeed Assessments provides skills tests that are not indicative of a license or certification or continued development in any professional field """
    res = NerText(sentence=text)
    print(res)